### ISSUE TITLE
TODO list for JaxPM 2.0

### ISSUE THREAD

**Issue by ASKabalan** [DifferentiableUniverseInitiative/JaxPM#25]
- [x] Fix painting issues when painting with absolute positions
- [x] Fix make ode API .. default behavior must be the old one
- [x] Add unit testing to check powerspec plus field MSE against FastPM

(Feel free to add more)

**Comment by ASKabalan** [comment]
Closing this issue as everything is implemented
